### ISSUE TITLE
[BUG] Code won't compile with netCDF output

### ISSUE THREAD

**Issue by aaronjridley** [AetherModel/Aether#50]
**Describe the bug**
The netCDF libraries don't seem to work with all compiler / OS combinations, so the code won't compile.

**To Reproduce**
Need to be on some architecture. For example, it doesn't seem to work with OSX and g++10/11? maybe?

**Expected behavior**
Code won't compile. 

**Screenshots**
Not going to add these.

**System information (please complete the following information):**
See above.

**Solution**
- Have implemented a Config.py script in the main directory to allow configuring the code now.
- Have made two types of outputs - netCDF (output_netcdf.cpp) and binary (output_binary.cpp). Config.py can choose which one is compiled (linked to output.cpp).
- output_binary.cpp outputs a binary file and a header (ascii) file.

**Still Needed**
- A python reader for the header/binary combo. Should be able to parse data file into variable names, variable units, time, etc, and read in the binary file, creating the proper 3D arrays. This could then be used for plotting if people want.
- A python writer for netCDF. This should take the parsed data that is read in and write out a netCDF that can be read by the normal aetherpy code.
- aetherpy should be modified so that if it gets a ".header" file or a ".bin" file, it looks for the other and reads the appropriate file combo. Remember, GITM uses *.bin files, so it needs to keep working with GITM as well as aether.

**Comment by qalshidi** [comment]
@aaronjridley since Armadillo has HDF5 capabilities why not switch NetCDF to HDF5? I've only had very very bad issues with NetCDF it's not easy on C++ and I think it's because of the proprietary nature of it.

**Comment by aaronjridley** [comment]
Yes, I agree. I would be more than happy for anyone to write an HDF5 output (using the outline of the output_ncdf and output_binary codes).  Then users can choose which type of output they would like.  Once there is a general template, these are very easy to maintain. We may eventually want to come up with a general output thing that loads variable names, units and data into a structure/class or something, and then we have a method that outputs all of that data in the right format.  That would be awesome to implement.  Hmmmm.... maybe an undergrad could do this?
