### ISSUE TITLE
[BUG] Armadillo in two places (one incorrect)

### ISSUE THREAD

**Issue by qalshidi** [AetherModel/Aether#64]
**Describe the bug**
Armadillo was included in `include/` folder when that should be strictly Aether stuff. Armadillo is already in `share/include/`

**Expected behavior**
No armadillo in `include/` folder

Will fix in my next pull request. CMake should recognize armadillo in new folder. If not then that can be a reported bug.

**Comment by aaronjridley** [comment]
I think that this is addressed through cmake now.
