### ISSUE TITLE
[FEAT] CMake

### ISSUE THREAD

**Issue by qalshidi** [AetherModel/Aether#7]
I think static Makefiles can be hard to use. We can keep the static makefile but
I believe we should also have a CMakeLists.txt to use CMake that can handle
dependencies well.

**Describe the solution you'd like**

Add a `CMakeLists.txt`

**Describe alternatives you've considered**

Just using a static Makefile but this might be hard to track all edge cases. And
might be reinventing the wheel.

**Additional context**

[CMake](https://cmake.org/) is a well known and well used software. I've used it before and can add it
and maintain it myself.

**Comment by aaronjridley** [comment]
This has been incorporated.
